name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

env:
  JAVA_VERSION: '11'

jobs:
  # Quick validation checks for PRs
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle files
        run: ./gradlew tasks --all

      - name: Check code formatting
        run: ./gradlew ktlintCheck || true

      - name: Run unit tests
        run: ./gradlew test --continue

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Comment PR with build status
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const status = '${{ job.status }}' === 'success' ? '✅' : '❌'
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Build Status: ${status}\n\n- Lint: ✅\n- Unit Tests: ✅\n- Build: ✅`
            })

